server:
  port: 10069
spring:
  application:
    name: msg
  rabbitmq:
    listener:
      #如果手动声明listener类型，可在config声明时设置
      direct:
        acknowledge-mode: MANUAL
      simple:
        acknowledge-mode: MANUAL
    host: 192.168.201.131
#eureka注册中心地址
eureka:
  instance:
    # 微服务实例IP地址
    instance-id: 127.0.0.1:${server.port}
    # 使用IP进行访问
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka/
